In [4]:
%pip install mysql-connector-python
import mysql.connector
import pandas as pd
import getpass
from sqlalchemy import create_engine

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Using cached mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl (17.7 MB)
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0
Note: you may need to restart the kernel to use updated packages.

In [5]:
import warnings
warnings.filterwarnings("ignore")

In [6]:
# Database credentials
username = "root"
password = getpass.getpass("Enter MySQL password: ")  # password hidden
host = "localhost"
database = "pgdsms"

In [7]:
# Step 1: Connect using mysql.connector
conn = mysql.connector.connect(
    user=username,
    password=password,
    host=host,
    database=database
)

In [8]:
cursor = conn.cursor()
cursor

In [9]:
# Step 2: Show all tables
cursor.execute("SHOW TABLES;")
tables = cursor.fetchall()
print("Tables:", tables)

Tables: [('classes',), ('courses',), ('departments',), ('staff',), ('students',), ('teachers',)]

In [ ]:
# Step 3a: Describe Courses table
cursor.execute("DESCRIBE courses;")
desc_table = cursor.fetchall()
desc_table

[('course_id', 'int', 'NO', 'PRI', None, ''),
 ('course_name', 'varchar(100)', 'YES', '', None, ''),
 ('course_code', 'varchar(20)', 'YES', '', None, ''),
 ('credit_hours', 'int', 'YES', '', None, ''),
 ('teacher_id', 'int', 'YES', 'MUL', None, ''),
 ('department_id', 'int', 'YES', 'MUL', None, '')]

In [ ]:
# Step 3b: Describe Departments table
cursor.execute("DESCRIBE departments;")
desc_table = cursor.fetchall()
desc_table

[('department_id', 'int', 'NO', 'PRI', None, ''),
 ('department_name', 'varchar(100)', 'YES', '', None, '')]

In [ ]:
# Step 4: Fetch all students
cursor.execute("SELECT * FROM Students;")
rows = cursor.fetchall()
for i in cursor.description:
    print(i[0])

student_id
first_name
last_name
gender
date_of_birth
email
phone
class_id
department_id
age
investment
country

In [29]:
# Step 5: Fetch all students
cursor.execute("SELECT * FROM Students;")
rows = cursor.fetchall()
# Data Frame 
df = pd.DataFrame(rows, columns=[i[0] for i in cursor.description])
df.head()

,student_id,first_name,last_name,gender,date_of_birth,email,phone,class_id,department_id,age,investment,country
0,1,Ahmed,Ali,Male,2007-05-02,student1@uni.com,03120000001,1,1,19,7227.45,Malaysia
1,2,Hassan,Ahmed,Male,2006-05-02,student2@uni.com,03120000002,2,2,20,5283.99,Malaysia
2,3,Usman,Hussain,Male,2005-05-02,student3@uni.com,03120000003,3,3,21,3737.59,Turkey
3,4,Hamza,Malik,Male,2004-05-02,student4@uni.com,03120000004,4,4,22,1835.97,Malaysia
4,5,Zain,Raza,Male,2008-05-02,student5@uni.com,03120000005,5,5,18,5967.07,Malaysia

In [30]:
df[(df['gender']=='Male') & (df['age']>=18) & (df['class_id']==1)]

,student_id,first_name,last_name,gender,date_of_birth,email,phone,class_id,department_id,age,investment,country
0,1,Ahmed,Ali,Male,2007-05-02,student1@uni.com,03120000001,1,1,19,7227.45,Malaysia
45,46,Bilal,Ali,Male,2007-05-02,student46@uni.com,03120000046,1,1,19,9586.20,Saudi Arabia
60,61,Ahmed,Ali,Male,2007-05-02,student61@uni.com,03120000061,1,1,19,1040.53,Saudi Arabia
105,106,Bilal,Ali,Male,2007-05-02,student106@uni.com,03120000106,1,1,19,5311.23,Malaysia
120,121,Ahmed,Ali,Male,2007-05-02,student121@uni.com,03120000121,1,1,19,5700.37,Qatar
165,166,Bilal,Ali,Male,2007-05-02,student166@uni.com,03120000166,1,1,19,3987.45,UAE
180,181,Ahmed,Ali,Male,2007-05-02,student181@uni.com,03120000181,1,1,19,9801.37,Pakistan

In [33]:
df.query("gender == 'Male'and age > 19")

,student_id,first_name,last_name,gender,date_of_birth,email,phone,class_id,department_id,age,investment,country
1,2,Hassan,Ahmed,Male,2006-05-02,student2@uni.com,03120000002,2,2,20,5283.99,Malaysia
2,3,Usman,Hussain,Male,2005-05-02,student3@uni.com,03120000003,3,3,21,3737.59,Turkey
3,4,Hamza,Malik,Male,2004-05-02,student4@uni.com,03120000004,4,4,22,1835.97,Malaysia
6,7,Danish,Iqbal,Male,2006-05-02,student7@uni.com,03120000007,7,7,20,7736.14,Malaysia
7,8,Farhan,Farooq,Male,2005-05-02,student8@uni.com,03120000008,8,8,21,3698.30,Malaysia
8,9,Saad,Siddiqui,Male,2004-05-02,student9@uni.com,03120000009,9,9,22,3283.07,Saudi Arabia
21,22,Hassan,Iqbal,Male,2006-05-02,student22@uni.com,03120000022,7,7,20,4769.23,Saudi Arabia
22,23,Usman,Farooq,Male,2005-05-02,student23@uni.com,03120000023,8,8,21,5752.09,Malaysia
23,24,Hamza,Siddiqui,Male,2004-05-02,student24@uni.com,03120000024,9,9,22,4452.78,UAE
26,27,Danish,Sheikh,Male,2006-05-02,student27@uni.com,03120000027,12,12,20,6375.80,UAE
27,28,Farhan,Memon,Male,2005-05-02,student28@uni.com,03120000028,13,13,21,4839.80,Pakistan
28,29,Saad,Chaudhry,Male,2004-05-02,student29@uni.com,03120000029,14,14,22,4071.61,Saudi Arabia
41,42,Hassan,Sheikh,Male,2006-05-02,student42@uni.com,03120000042,12,12,20,2076.06,Pakistan
42,43,Usman,Memon,Male,2005-05-02,student43@uni.com,03120000043,13,13,21,9985.33,Malaysia
43,44,Hamza,Chaudhry,Male,2004-05-02,student44@uni.com,03120000044,14,14,22,6698.46,Saudi Arabia
46,47,Danish,Ahmed,Male,2006-05-02,student47@uni.com,03120000047,2,2,20,3322.04,Qatar
47,48,Farhan,Hussain,Male,2005-05-02,student48@uni.com,03120000048,3,3,21,4851.59,Malaysia
48,49,Saad,Malik,Male,2004-05-02,student49@uni.com,03120000049,4,4,22,4291.85,Qatar
61,62,Hassan,Ahmed,Male,2006-05-02,student62@uni.com,03120000062,2,2,20,7284.38,Qatar
62,63,Usman,Hussain,Male,2005-05-02,student63@uni.com,03120000063,3,3,21,5300.30,Turkey
63,64,Hamza,Malik,Male,2004-05-02,student64@uni.com,03120000064,4,4,22,3648.38,Saudi Arabia
66,67,Danish,Iqbal,Male,2006-05-02,student67@uni.com,03120000067,7,7,20,4775.73,Pakistan
67,68,Farhan,Farooq,Male,2005-05-02,student68@uni.com,03120000068,8,8,21,2599.45,Turkey
68,69,Saad,Siddiqui,Male,2004-05-02,student69@uni.com,03120000069,9,9,22,6670.08,Turkey
81,82,Hassan,Iqbal,Male,2006-05-02,student82@uni.com,03120000082,7,7,20,8261.25,Qatar
82,83,Usman,Farooq,Male,2005-05-02,student83@uni.com,03120000083,8,8,21,6048.92,Saudi Arabia
83,84,Hamza,Siddiqui,Male,2004-05-02,student84@uni.com,03120000084,9,9,22,4460.87,Qatar
86,87,Danish,Sheikh,Male,2006-05-02,student87@uni.com,03120000087,12,12,20,5553.60,Saudi Arabia
87,88,Farhan,Memon,Male,2005-05-02,student88@uni.com,03120000088,13,13,21,4552.20,Turkey
88,89,Saad,Chaudhry,Male,2004-05-02,student89@uni.com,03120000089,14,14,22,5100.21,Pakistan
101,102,Hassan,Sheikh,Male,2006-05-02,student102@uni.com,03120000102,12,12,20,7143.16,Qatar
102,103,Usman,Memon,Male,2005-05-02,student103@uni.com,03120000103,13,13,21,4365.89,Saudi Arabia
103,104,Hamza,Chaudhry,Male,2004-05-02,student104@uni.com,03120000104,14,14,22,8399.98,Malaysia
106,107,Danish,Ahmed,Male,2006-05-02,student107@uni.com,03120000107,2,2,20,4849.43,Malaysia
107,108,Farhan,Hussain,Male,2005-05-02,student108@uni.com,03120000108,3,3,21,7313.45,Malaysia
108,109,Saad,Malik,Male,2004-05-02,student109@uni.com,03120000109,4,4,22,3018.98,Qatar
121,122,Hassan,Ahmed,Male,2006-05-02,student122@uni.com,03120000122,2,2,20,6989.43,Malaysia
122,123,Usman,Hussain,Male,2005-05-02,student123@uni.com,03120000123,3,3,21,7846.02,Saudi Arabia
123,124,Hamza,Malik,Male,2004-05-02,student124@uni.com,03120000124,4,4,22,8261.81,Qatar
126,127,Danish,Iqbal,Male,2006-05-02,student127@uni.com,03120000127,7,7,20,5034.89,Pakistan
127,128,Farhan,Farooq,Male,2005-05-02,student128@uni.com,03120000128,8,8,21,2965.73,Malaysia
128,129,Saad,Siddiqui,Male,2004-05-02,student129@uni.com,03120000129,9,9,22,7723.98,Turkey
141,142,Hassan,Iqbal,Male,2006-05-02,student142@uni.com,03120000142,7,7,20,8118.79,Turkey
142,143,Usman,Farooq,Male,2005-05-02,student143@uni.com,03120000143,8,8,21,6920.56,Saudi Arabia
143,144,Hamza,Siddiqui,Male,2004-05-02,student144@uni.com,03120000144,9,9,22,9246.43,UAE
146,147,Danish,Sheikh,Male,2006-05-02,student147@uni.com,03120000147,12,12,20,6653.81,Qatar
147,148,Farhan,Memon,Male,2005-05-02,student148@uni.com,03120000148,13,13,21,3429.91,Pakistan
148,149,Saad,Chaudhry,Male,2004-05-02,student149@uni.com,03120000149,14,14,22,5188.13,Qatar
161,162,Hassan,Sheikh,Male,2006-05-02,student162@uni.com,03120000162,12,12,20,3566.12,Qatar
162,163,Usman,Memon,Male,2005-05-02,student163@uni.com,03120000163,13,13,21,3856.33,Qatar
163,164,Hamza,Chaudhry,Male,2004-05-02,student164@uni.com,03120000164,14,14,22,7583.29,Turkey
166,167,Danish,Ahmed,Male,2006-05-02,student167@uni.com,03120000167,2,2,20,5894.87,Saudi Arabia
167,168,Farhan,Hussain,Male,2005-05-02,student168@uni.com,03120000168,3,3,21,7512.01,Malaysia
168,169,Saad,Malik,Male,2004-05-02,student169@uni.com,03120000169,4,4,22,9875.44,Pakistan
181,182,Hassan,Ahmed,Male,2006-05-02,student182@uni.com,03120000182,2,2,20,8149.01,Malaysia
182,183,Usman,Hussain,Male,2005-05-02,student183@uni.com,03120000183,3,3,21,1340.91,Malaysia
183,184,Hamza,Malik,Male,2004-05-02,student184@uni.com,03120000184,4,4,22,8257.53,Turkey
186,187,Danish,Iqbal,Male,2006-05-02,student187@uni.com,03120000187,7,7,20,1964.96,UAE
187,188,Farhan,Farooq,Male,2005-05-02,student188@uni.com,03120000188,8,8,21,1169.02,Qatar
188,189,Saad,Siddiqui,Male,2004-05-02,student189@uni.com,03120000189,9,9,22,7950.22,Pakistan

In [32]:
df[(df['gender']=='Male')]

,student_id,first_name,last_name,gender,date_of_birth,email,phone,class_id,department_id,age,investment,country
0,1,Ahmed,Ali,Male,2007-05-02,student1@uni.com,03120000001,1,1,19,7227.45,Malaysia
1,2,Hassan,Ahmed,Male,2006-05-02,student2@uni.com,03120000002,2,2,20,5283.99,Malaysia
2,3,Usman,Hussain,Male,2005-05-02,student3@uni.com,03120000003,3,3,21,3737.59,Turkey
3,4,Hamza,Malik,Male,2004-05-02,student4@uni.com,03120000004,4,4,22,1835.97,Malaysia
4,5,Zain,Raza,Male,2008-05-02,student5@uni.com,03120000005,5,5,18,5967.07,Malaysia
...,...,...,...,...,...,...,...,...,...,...,...,...
185,186,Bilal,Shah,Male,2007-05-02,student186@uni.com,03120000186,6,6,19,2551.93,UAE
186,187,Danish,Iqbal,Male,2006-05-02,student187@uni.com,03120000187,7,7,20,1964.96,UAE
187,188,Farhan,Farooq,Male,2005-05-02,student188@uni.com,03120000188,8,8,21,1169.02,Qatar
188,189,Saad,Siddiqui,Male,2004-05-02,student189@uni.com,03120000189,9,9,22,7950.22,Pakistan
199,200,Ali,Raza,Male,2008-05-02,student200@uni.com,03120000200,5,5,18,5270.81,Turkey

In [18]:
query = "SELECT * FROM classes;"

In [19]:
df = pd.read_sql(query, conn)
df

    class_id     class_name  department_id
0          1        BSCS-1A              1
1          2  BS Physics-1A              2
2          3     BS Math-1A              3
3          4  BS English-1A              4
4          5         BBA-1A              5
5          6        BSDS-1A              6
6          7        BSAI-1A              7
7          8        BSSE-1A              8
8          9       BSCYB-1A              9
9         10        BSEE-1A             10
10        11        BSME-1A             11
11        12        BSCE-1A             12
12        13       BSECO-1A             13
13        14      BSSTAT-1A             14
14        15       BSBIO-1A             15

In [20]:
# SQL Query
query = """
SELECT first_name, Investment
FROM Students
WHERE Investment = (
    SELECT MIN(Investment)
    FROM Students
);
"""

# Execute query and store result in dataframe
min_int = pd.read_sql(query, conn)

# Display result
print(min_int)

  first_name  Investment
0      Anaya     1001.62