In [62]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns",None)
print("Pandas version",pd.__version__)
print("Numpy version",np.__version__)

Pandas version 3.0.6
Numpy version 2.5.3

In [63]:
#create datafram and series
df=pd.DataFrame({
    'Name': ['Ali', 'Sara', 'Ahmed', 'Ayesha', 'Bilal'],
    'Age': [25, 30, 28, 35, 22],
    'Salary': [50000, 70000, 60000, 90000, 45000],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR']
})
df

     Name  Age  Salary Department
0     Ali   25   50000         IT
1    Sara   30   70000         HR
2   Ahmed   28   60000         IT
3  Ayesha   35   90000    Finance
4   Bilal   22   45000         HR

In [64]:
# Create a DataFrame from a list of lists
df_list=pd.DataFrame( [
        ['Ali', 25, 50000],
        ['Sara', 30, 70000],
        ['Ahmed', 28, 60000]
    ],
    columns=['Name','Age','Salary'])
df_list

    Name  Age  Salary
0    Ali   25   50000
1   Sara   30   70000
2  Ahmed   28   60000

In [65]:
s=pd.Series([10,20,30,40,50],name='Numbers')
s

0    10
1    20
2    30
3    40
4    50
Name: Numbers, dtype: int64

In [66]:
ages=pd.Series([25,30,45,71],)
print(ages.mean())
print(ages.max())
print(ages[ages>30])

42.75
71
2    45
3    71
dtype: int64

In [67]:
# Read a CSV file
# df = pd.read_csv('data.csv')

# Read an Excel file
# df = pd.read_excel('data.xlsx')

# Read JSON
# df = pd.read_json('data.json')

# Read data from SQL (requires a database connection)
#df = pd.read_sql('SELECT * FROM customers', connection)

# Read tabular data copied to the clipboard
# df = pd.read_clipboard()

print("Uncomment the required command when the corresponding file/database is available.")

Uncomment the required command when the corresponding file/database is available.

In [68]:
# Save DataFrame to CSV
# df.to_csv('output.csv', index=False)

# Save DataFrame to Excel
# df.to_excel('output.xlsx', index=False)

# Save DataFrame to JSON
# df.to_json('output.json')

# Save DataFrame to SQL
# df.to_sql('customers', connection, if_exists='replace', index=False)

print("Export examples are commented so the notebook does not overwrite files accidentally.")

Export examples are commented so the notebook does not overwrite files accidentally.

In [69]:

from IPython.display import display
print("HEAD:")
display(df.head())

# First 3 rows
print("HEAD(3):")
display(df.head(3))

# Last 5 rows

# Number of rows and columns
print("Shape:", df.shape)


print("Shape",df.shape)

print("Tail")
display(df.tail())
print("Descriptive summary")
display(df.describe())

print("Info :")
display(df.info())

print("All summary comlums")
display(df.describe(include='all'))

print("Unique number")
print(df.nunique())

HEAD:

     Name  Age  Salary Department
0     Ali   25   50000         IT
1    Sara   30   70000         HR
2   Ahmed   28   60000         IT
3  Ayesha   35   90000    Finance
4   Bilal   22   45000         HR

HEAD(3):

    Name  Age  Salary Department
0    Ali   25   50000         IT
1   Sara   30   70000         HR
2  Ahmed   28   60000         IT

Shape: (5, 4)
Shape (5, 4)
Tail

     Name  Age  Salary Department
0     Ali   25   50000         IT
1    Sara   30   70000         HR
2   Ahmed   28   60000         IT
3  Ayesha   35   90000    Finance
4   Bilal   22   45000         HR

Descriptive summary

             Age       Salary
count   5.000000      5.00000
mean   28.000000  63000.00000
std     4.949747  17888.54382
min    22.000000  45000.00000
25%    25.000000  50000.00000
50%    28.000000  60000.00000
75%    30.000000  70000.00000
max    35.000000  90000.00000

Info :
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      str
 1   Age         5 non-null      int64
 2   Salary      5 non-null      int64
 3   Department  5 non-null      str
dtypes: int64(2), str(2)
memory usage: 330.0 bytes

None

All summary comlums

       Name        Age       Salary Department
count     5   5.000000      5.00000          5
unique    5        NaN          NaN          3
top     Ali        NaN          NaN         IT
freq      1        NaN          NaN          2
mean    NaN  28.000000  63000.00000        NaN
std     NaN   4.949747  17888.54382        NaN
min     NaN  22.000000  45000.00000        NaN
25%     NaN  25.000000  50000.00000        NaN
50%     NaN  28.000000  60000.00000        NaN
75%     NaN  30.000000  70000.00000        NaN
max     NaN  35.000000  90000.00000        NaN

Unique number
Name          5
Age           5
Salary        5
Department    3
dtype: int64

In [70]:
# Select one column
display(df['Age'])

# Select multiple columns
display(df[['Name', 'Age', 'Salary']])

# Dot notation works for simple column names
display(df.Age)

# Recommended general approach:
# df['Age']

0    25
1    30
2    28
3    35
4    22
Name: Age, dtype: int64

     Name  Age  Salary
0     Ali   25   50000
1    Sara   30   70000
2   Ahmed   28   60000
3  Ayesha   35   90000
4   Bilal   22   45000

0    25
1    30
2    28
3    35
4    22
Name: Age, dtype: int64

In [71]:
# Select the first row by position

display(df.iloc[0])
display(df.iloc[:5])
display(df.iloc[[0,2,4]])

print("Cell at row 0, column 1:", df.iloc[0, 1])
display(df.loc[0:2,["Name","Age"]])

Name            Ali
Age              25
Salary        50000
Department       IT
Name: 0, dtype: object

     Name  Age  Salary Department
0     Ali   25   50000         IT
1    Sara   30   70000         HR
2   Ahmed   28   60000         IT
3  Ayesha   35   90000    Finance
4   Bilal   22   45000         HR

    Name  Age  Salary Department
0    Ali   25   50000         IT
2  Ahmed   28   60000         IT
4  Bilal   22   45000         HR

Cell at row 0, column 1: 25

    Name  Age
0    Ali   25
1   Sara   30
2  Ahmed   28

In [72]:
# Filter Age > 25
display(df[df['Age'] > 25])

# Filter Salary > 50,000
display(df[df['Salary'] > 50000])

# AND condition: both conditions must be true
display(df[(df['Age'] > 25) & (df['Salary'] > 50000)])

# OR condition: at least one condition must be true
display(df[(df['Age'] > 25) | (df['Salary'] > 50000)])

# NOT condition
display(df[~(df['Age']>25)])

     Name  Age  Salary Department
1    Sara   30   70000         HR
2   Ahmed   28   60000         IT
3  Ayesha   35   90000    Finance

     Name  Age  Salary Department
1    Sara   30   70000         HR
2   Ahmed   28   60000         IT
3  Ayesha   35   90000    Finance

     Name  Age  Salary Department
1    Sara   30   70000         HR
2   Ahmed   28   60000         IT
3  Ayesha   35   90000    Finance

     Name  Age  Salary Department
1    Sara   30   70000         HR
2   Ahmed   28   60000         IT
3  Ayesha   35   90000    Finance

    Name  Age  Salary Department
0    Ali   25   50000         IT
4  Bilal   22   45000         HR

In [73]:
display(df[df["Department"].isin(["IT","HR"])])

display(df[~(df["Department"].isin(["IT","HR"]))])

display(df[df['Age'].between(25,30)])
display(df.query("Age > 25 and Salary > 50000"))

    Name  Age  Salary Department
0    Ali   25   50000         IT
1   Sara   30   70000         HR
2  Ahmed   28   60000         IT
4  Bilal   22   45000         HR

     Name  Age  Salary Department
3  Ayesha   35   90000    Finance

    Name  Age  Salary Department
0    Ali   25   50000         IT
1   Sara   30   70000         HR
2  Ahmed   28   60000         IT

     Name  Age  Salary Department
1    Sara   30   70000         HR
2   Ahmed   28   60000         IT
3  Ayesha   35   90000    Finance

In [74]:
df['AnnualSalary'] = df['Salary'] * 12

# Add a tax column
df['Tax'] = df['Salary'] * 0.10

df["Adult"]=np.where(df['Age']>=18,'Yes','No')
display(df)

     Name  Age  Salary Department  AnnualSalary     Tax Adult
0     Ali   25   50000         IT        600000  5000.0   Yes
1    Sara   30   70000         HR        840000  7000.0   Yes
2   Ahmed   28   60000         IT        720000  6000.0   Yes
3  Ayesha   35   90000    Finance       1080000  9000.0   Yes
4   Bilal   22   45000         HR        540000  4500.0   Yes

In [75]:
# Multiple conditions using np.select()
conditions=[
    df['Salary']>80000,
    df['Salary']>60000,
    df['Salary']>50000
]
choices=['High','Medium','Standard']
df['Salary_Catogart']=np.select(conditions,choices,default='low')
df

     Name  Age  Salary Department  AnnualSalary     Tax Adult Salary_Catogart
0     Ali   25   50000         IT        600000  5000.0   Yes             low
1    Sara   30   70000         HR        840000  7000.0   Yes          Medium
2   Ahmed   28   60000         IT        720000  6000.0   Yes        Standard
3  Ayesha   35   90000    Finance       1080000  9000.0   Yes            High
4   Bilal   22   45000         HR        540000  4500.0   Yes             low

In [76]:
df_without_tax=df.drop(columns=['Tax','Adult'])
display(df_without_tax)

     Name  Age  Salary Department  AnnualSalary Salary_Catogart
0     Ali   25   50000         IT        600000             low
1    Sara   30   70000         HR        840000          Medium
2   Ahmed   28   60000         IT        720000        Standard
3  Ayesha   35   90000    Finance       1080000            High
4   Bilal   22   45000         HR        540000             low

In [81]:
# Add a single row using loc
df_rows = df[['Name', 'Age', 'Salary', 'Department']].copy()

df_rows.loc[len(df_rows)] = [
    'Hamza', 27, 55000, 'IT'
]

display(df_rows)

     Name  Age  Salary Department
0     Ali   25   50000         IT
1    Sara   30   70000         HR
2   Ahmed   28   60000         IT
3  Ayesha   35   90000    Finance
4   Bilal   22   45000         HR
5   Hamza   27   55000         IT

In [84]:
df1=pd.DataFrame({
    'Name':['sara','umer'],
    'Salary':[56000,23000]

})
df2=pd.DataFrame({
    'Name':['Ali','dawood'],
    'Salary':[3400,63000]

})
combined=pd.concat([df1,df2],ignore_index=True)
display(combined)

     Name  Salary
0    sara   56000
1    umer   23000
2     Ali    3400
3  dawood   63000

In [89]:
renamed=df.rename(columns={
    'Age':'Customer_Age',
    'Salary':"Customer Salary"
})
display(renamed.head())

,Name,Customer_Age,Customer Salary,Department,AnnualSalary,Tax,Adult,Salary_Catogart
0,Ali,25,50000,IT,600000,5000.0,Yes,low
1,Sara,30,70000,HR,840000,7000.0,Yes,Medium
2,Ahmed,28,60000,IT,720000,6000.0,Yes,Standard
3,Ayesha,35,90000,Finance,1080000,9000.0,Yes,High
4,Bilal,22,45000,HR,540000,4500.0,Yes,low

In [ ]:
display(df.sort_values('Salary',ascending=False))

     Name  Age  Salary Department  AnnualSalary     Tax Adult Salary_Catogart
3  Ayesha   35   90000    Finance       1080000  9000.0   Yes            High
1    Sara   30   70000         HR        840000  7000.0   Yes          Medium
2   Ahmed   28   60000         IT        720000  6000.0   Yes        Standard
0     Ali   25   50000         IT        600000  5000.0   Yes             low
4   Bilal   22   45000         HR        540000  4500.0   Yes             low

In [92]:
display(
    df.sort_values(
        ['Department','Salary'],ascending=(True,False)
    )
)

     Name  Age  Salary Department  AnnualSalary     Tax Adult Salary_Catogart
3  Ayesha   35   90000    Finance       1080000  9000.0   Yes            High
1    Sara   30   70000         HR        840000  7000.0   Yes          Medium
4   Bilal   22   45000         HR        540000  4500.0   Yes             low
2   Ahmed   28   60000         IT        720000  6000.0   Yes        Standard
0     Ali   25   50000         IT        600000  5000.0   Yes             low

In [97]:
# Create a small DataFrame containing missing values
missing_df=pd.DataFrame({
        'Name': ['Ali', 'Sara', 'Ahmed', 'Ayesha'],
    'Age': [25, np.nan, 28, 35],
    'Salary': [50000, 70000, np.nan, 90000]
})
display(missing_df.isna())

print(missing_df.isna().sum())
print(missing_df.isna().mean()*100)
display(missing_df.dropna())
display(missing_df.fillna(0))
ms=missing_df.isna().mean()*100
display(missing_df.fillna(ms))

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False  False   False

Name      0
Age       1
Salary    1
dtype: int64
Name       0.0
Age       25.0
Salary    25.0
dtype: float64

     Name   Age   Salary
0     Ali  25.0  50000.0
3  Ayesha  35.0  90000.0

     Name   Age   Salary
0     Ali  25.0  50000.0
1    Sara   0.0  70000.0
2   Ahmed  28.0      0.0
3  Ayesha  35.0  90000.0

     Name   Age   Salary
0     Ali  25.0  50000.0
1    Sara  25.0  70000.0
2   Ahmed  28.0     25.0
3  Ayesha  35.0  90000.0

In [104]:
# Fill Age missing values with the median
missing_df['Age']=missing_df['Age'].fillna(
    missing_df['Age'].median()
)
# Fill Salary missing values with the mean
missing_df["Salary"]=missing_df['Salary'].fillna(
    missing_df['Salary'].mean()
)
display(missing_df)

     Name   Age   Salary
0     Ali  25.0  50000.0
1    Sara  28.0  70000.0
2   Ahmed  28.0  70000.0
3  Ayesha  35.0  90000.0

In [112]:
duplicate_df=pd.DataFrame({
    'Customer_id':[101, 102, 102, 103, 104, 104],
    'Name':['Ali', 'Sara', 'Sara', 'Ahmed', 'Ayesha', 'Ayesha']

})
print("Duplicated count",duplicate_df.duplicated().sum())
cleaned_dup=duplicate_df.drop_duplicates()
display(cleaned_dup)
display(duplicate_df.drop_duplicates(subset=['Customer_id']))

Duplicated count 2

   Customer_id    Name
0          101     Ali
1          102    Sara
3          103   Ahmed
4          104  Ayesha

   Customer_id    Name
0          101     Ali
1          102    Sara
3          103   Ahmed
4          104  Ayesha

In [113]:
text_df = pd.DataFrame({
    'Name': [' ali ', 'SARA', 'Ahmed Khan', 'Ayesha'],
    'Email': ['ALI@EXAMPLE.COM', 'sara@test.com', 'ahmed@test.com', 'ayesha@test.com']
})

# Convert to lowercase
text_df['Name_Lower'] = text_df['Name'].str.lower()

# Convert to uppercase
text_df['Name_Upper'] = text_df['Name'].str.upper()

# Capitalize
text_df['Name_Capitalized'] = text_df['Name'].str.capitalize()

# Remove leading/trailing spaces
text_df['Name_Clean'] = text_df['Name'].str.strip()

# String length
text_df['Name_Length'] = text_df['Name'].str.len()

display(text_df)

,Name,Email,Name_Lower,Name_Upper,Name_Capitalized,Name_Clean,Name_Length
0,ali,ALI@EXAMPLE.COM,ali,ALI,ali,ali,5
1,SARA,sara@test.com,sara,SARA,Sara,SARA,4
2,Ahmed Khan,ahmed@test.com,ahmed khan,AHMED KHAN,Ahmed khan,Ahmed Khan,10
3,Ayesha,ayesha@test.com,ayesha,AYESHA,Ayesha,Ayesha,6

In [ ]:
#contains

display(
    text_df[
        text_df['Name'].str.contains('Ali', case=False, na=False)
    ]
)
display(
    text_df[
        text_df['Name'].str.strip().str.startswith('A',na=False)
    ]
)
display(
    
        text_df['Name'].str.replace('Ali','Ahmed',regex=False)
    
)
display(
    text_df['Name']
)

,Name,Email,Name_Lower,Name_Upper,Name_Capitalized,Name_Clean,Name_Length
0,ali,ALI@EXAMPLE.COM,ali,ALI,ali,ali,5

,Name,Email,Name_Lower,Name_Upper,Name_Capitalized,Name_Clean,Name_Length
2,Ahmed Khan,ahmed@test.com,ahmed khan,AHMED KHAN,Ahmed khan,Ahmed Khan,10
3,Ayesha,ayesha@test.com,ayesha,AYESHA,Ayesha,Ayesha,6

0          ali
1          SARA
2    Ahmed Khan
3        Ayesha
Name: Name, dtype: str