# 🐼 Pandas Complete Practical Code Reference

A practical, commented Pandas notebook covering:

- Creating DataFrames and Series
- Reading and writing CSV, Excel, JSON and SQL data
- Data inspection and exploration
- Selecting, filtering and sorting
- Adding, modifying and removing columns
- Missing values and duplicates
- String and date/time operations
- Statistics and correlation
- GroupBy and aggregation
- Apply, map and conditional transformations
- Merge, concat and reshaping
- Pivot tables and crosstabs
- Sampling and train/test preparation
- Outlier detection
- Rolling, cumulative and time-series operations
- Encoding and binning
- Large-file handling
- Machine-learning preparation

> Tip: Run the setup and sample-data cells first. File/database examples that require external files or connections are provided as commented templates.

In [1]:
%pip install pandas
%pip install numpy

Requirement already satisfied: pandas in /home/bakar/Documents/NAVTTC/.venv/lib/python3.12/site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in /home/bakar/Documents/NAVTTC/.venv/lib/python3.12/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/bakar/Documents/NAVTTC/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/bakar/Documents/NAVTTC/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in /home/bakar/Documents/NAVTTC/.venv/lib/python3.12/site-packages (2.5.3)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Import the main libraries used throughout this notebook
import pandas as pd
import numpy as np

# Optional: display more columns when working with wider DataFrames
pd.set_option('display.max_columns', None)

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Pandas version: 3.0.6
NumPy version: 2.5.3

## 1. Creating DataFrames and Series

In [3]:
# Create a DataFrame from a dictionary
df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'Ahmed', 'Ayesha', 'Bilal'],
    'Age': [25, 30, 28, 35, 22],
    'Salary': [50000, 70000, 60000, 90000, 45000],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR']
})

df

     Name  Age  Salary Department
0     Ali   25   50000         IT
1    Sara   30   70000         HR
2   Ahmed   28   60000         IT
3  Ayesha   35   90000    Finance
4   Bilal   22   45000         HR

In [4]:
# Create a DataFrame from a list of lists
df_list = pd.DataFrame(
    [
        ['Ali', 25, 50000],
        ['Sara', 30, 70000],
        ['Ahmed', 28, 60000]
    ],
    columns=['Name', 'Age', 'Salary']
)
    
df_list

    Name  Age  Salary
0    Ali   25   50000
1   Sara   30   70000
2  Ahmed   28   60000

In [5]:
# Create a Pandas Series
s = pd.Series([10, 20, 30, 40, 50], name='Numbers')
s

0    10
1    20
2    30
3    40
4    50
Name: Numbers, dtype: int64

In [6]:
ages = pd.Series([25, 30, 28, 35])

print(ages.mean())   # Average
print(ages.max())    # Highest value
print(ages[ages > 28])  # Filter values

29.5
35
1    30
3    35
dtype: int64

## 2. Reading Data

In [7]:
# Read a CSV file
# df = pd.read_csv('data.csv')

# Read an Excel file
# df = pd.read_excel('data.xlsx')

# Read JSON
# df = pd.read_json('data.json')

# Read data from SQL (requires a database connection)
#df = pd.read_sql('SELECT * FROM customers', connection)

# Read tabular data copied to the clipboard
# df = pd.read_clipboard()

print("Uncomment the required command when the corresponding file/database is available.")

Uncomment the required command when the corresponding file/database is available.

## 3. Saving / Exporting Data

In [8]:
# Save DataFrame to CSV
# df.to_csv('output.csv', index=False)

# Save DataFrame to Excel
# df.to_excel('output.xlsx', index=False)

# Save DataFrame to JSON
# df.to_json('output.json')

# Save DataFrame to SQL
# df.to_sql('customers', connection, if_exists='replace', index=False)

print("Export examples are commented so the notebook does not overwrite files accidentally.")

Export examples are commented so the notebook does not overwrite files accidentally.

## 4. Understanding Your Data

In [9]:
# First 5 rows
print("HEAD:")
display(df.head())

# First 3 rows
print("HEAD(3):")
display(df.head(3))

# Last 5 rows
print("TAIL:")
display(df.tail())

# Number of rows and columns
print("Shape:", df.shape)

# Column names
print("Columns:", df.columns.tolist())

# Index
print("Index:", df.index)

# Data types
print("\nData types:")
print(df.dtypes)

# Structure and non-null information
print("\nInfo:")
df.info()

# Statistical summary
print("\nDescriptive statistics:")
display(df.describe())

# Summary including categorical columns
print("\nAll-column summary:")
display(df.describe(include='all'))

# Number of unique values in every column
print("\nUnique counts:")
print(df.nunique())

HEAD:

     Name  Age  Salary Department
0     Ali   25   50000         IT
1    Sara   30   70000         HR
2   Ahmed   28   60000         IT
3  Ayesha   35   90000    Finance
4   Bilal   22   45000         HR

HEAD(3):

    Name  Age  Salary Department
0    Ali   25   50000         IT
1   Sara   30   70000         HR
2  Ahmed   28   60000         IT

TAIL:

     Name  Age  Salary Department
0     Ali   25   50000         IT
1    Sara   30   70000         HR
2   Ahmed   28   60000         IT
3  Ayesha   35   90000    Finance
4   Bilal   22   45000         HR

Shape: (5, 4)
Columns: ['Name', 'Age', 'Salary', 'Department']
Index: RangeIndex(start=0, stop=5, step=1)

Data types:
Name            str
Age           int64
Salary        int64
Department      str
dtype: object

Info:
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      str
 1   Age         5 non-null      int64
 2   Salary      5 non-null      int64
 3   Department  5 non-null      str
dtypes: int64(2), str(2)
memory usage: 330.0 bytes

Descriptive statistics:

             Age       Salary
count   5.000000      5.00000
mean   28.000000  63000.00000
std     4.949747  17888.54382
min    22.000000  45000.00000
25%    25.000000  50000.00000
50%    28.000000  60000.00000
75%    30.000000  70000.00000
max    35.000000  90000.00000

All-column summary:

       Name        Age       Salary Department
count     5   5.000000      5.00000          5
unique    5        NaN          NaN          3
top     Ali        NaN          NaN         IT
freq      1        NaN          NaN          2
mean    NaN  28.000000  63000.00000        NaN
std     NaN   4.949747  17888.54382        NaN
min     NaN  22.000000  45000.00000        NaN
25%     NaN  25.000000  50000.00000        NaN
50%     NaN  28.000000  60000.00000        NaN
75%     NaN  30.000000  70000.00000        NaN
max     NaN  35.000000  90000.00000        NaN

Unique counts:
Name          5
Age           5
Salary        5
Department    3
dtype: int64

## 5. Selecting Columns

In [10]:
# Select one column
display(df['Age'])

# Select multiple columns
display(df[['Name', 'Age', 'Salary']])

# Dot notation works for simple column names
display(df.Age)

# Recommended general approach:
# df['Age']

0    25
1    30
2    28
3    35
4    22
Name: Age, dtype: int64

     Name  Age  Salary
0     Ali   25   50000
1    Sara   30   70000
2   Ahmed   28   60000
3  Ayesha   35   90000
4   Bilal   22   45000

0    25
1    30
2    28
3    35
4    22
Name: Age, dtype: int64

## 6. Selecting Rows with iloc and loc

In [11]:
# Select the first row by position
display(df.iloc[0])

# Select the first five rows
display(df.iloc[:5])

# Select specific rows
display(df.iloc[[0, 2, 4]])

# Select one cell: row 0, column 1
print("Cell at row 0, column 1:", df.iloc[0, 1])

# Select rows/columns by labels
display(df.loc[0:2, ['Name', 'Age']])

Name            Ali
Age              25
Salary        50000
Department       IT
Name: 0, dtype: object

     Name  Age  Salary Department
0     Ali   25   50000         IT
1    Sara   30   70000         HR
2   Ahmed   28   60000         IT
3  Ayesha   35   90000    Finance
4   Bilal   22   45000         HR

    Name  Age  Salary Department
0    Ali   25   50000         IT
2  Ahmed   28   60000         IT
4  Bilal   22   45000         HR

Cell at row 0, column 1: 25

    Name  Age
0    Ali   25
1   Sara   30
2  Ahmed   28

## 7. Filtering Data

In [12]:
# Filter Age > 25
display(df[df['Age'] > 25])

# Filter Salary > 50,000
display(df[df['Salary'] > 50000])

# AND condition: both conditions must be true
display(df[(df['Age'] > 25) & (df['Salary'] > 50000)])

# OR condition: at least one condition must be true
display(df[(df['Age'] > 25) | (df['Salary'] > 50000)])

# NOT condition
display(df[~(df['Age'] > 25)])

     Name  Age  Salary Department
1    Sara   30   70000         HR
2   Ahmed   28   60000         IT
3  Ayesha   35   90000    Finance

     Name  Age  Salary Department
1    Sara   30   70000         HR
2   Ahmed   28   60000         IT
3  Ayesha   35   90000    Finance

     Name  Age  Salary Department
1    Sara   30   70000         HR
2   Ahmed   28   60000         IT
3  Ayesha   35   90000    Finance

     Name  Age  Salary Department
1    Sara   30   70000         HR
2   Ahmed   28   60000         IT
3  Ayesha   35   90000    Finance

    Name  Age  Salary Department
0    Ali   25   50000         IT
4  Bilal   22   45000         HR

## 8. isin(), between() and query()

In [13]:
# Filter rows where Department is IT or HR
display(df[df['Department'].isin(['IT', 'HR'])])

# NOT in a list
display(df[~df['Department'].isin(['IT', 'HR'])])

# Filter a numeric range
display(df[df['Age'].between(25, 30)])

# query() provides a readable alternative
display(df.query("Age > 25 and Salary > 50000"))

    Name  Age  Salary Department
0    Ali   25   50000         IT
1   Sara   30   70000         HR
2  Ahmed   28   60000         IT
4  Bilal   22   45000         HR

     Name  Age  Salary Department
3  Ayesha   35   90000    Finance

    Name  Age  Salary Department
0    Ali   25   50000         IT
1   Sara   30   70000         HR
2  Ahmed   28   60000         IT

     Name  Age  Salary Department
1    Sara   30   70000         HR
2   Ahmed   28   60000         IT
3  Ayesha   35   90000    Finance

## 9. Adding and Transforming Columns

In [14]:
# Add a calculated column
df['AnnualSalary'] = df['Salary'] * 12

# Add a tax column
df['Tax'] = df['Salary'] * 0.10

# Add a conditional column using np.where()
df['Adult'] = np.where(df['Age'] >= 18, 'Yes', 'No')

display(df)

     Name  Age  Salary Department  AnnualSalary     Tax Adult
0     Ali   25   50000         IT        600000  5000.0   Yes
1    Sara   30   70000         HR        840000  7000.0   Yes
2   Ahmed   28   60000         IT        720000  6000.0   Yes
3  Ayesha   35   90000    Finance       1080000  9000.0   Yes
4   Bilal   22   45000         HR        540000  4500.0   Yes

In [15]:
# Multiple conditions using np.select()
conditions = [
    df['Salary'] >= 80000,
    df['Salary'] >= 60000,
    df['Salary'] >= 50000
]

choices = ['High', 'Medium', 'Standard']

df['SalaryCategory'] = np.select(
    conditions,
    choices,
    default='Low'
)

display(df[['Name', 'Salary', 'SalaryCategory']])

     Name  Salary SalaryCategory
0     Ali   50000       Standard
1    Sara   70000         Medium
2   Ahmed   60000         Medium
3  Ayesha   90000           High
4   Bilal   45000            Low

## 10. Removing Columns

In [16]:
# Remove one column and return a new DataFrame
df_without_tax = df.drop(columns=['Tax'])

# Remove multiple columns
df_without_two = df.drop(columns=['Tax', 'Adult'])

display(df_without_two)

# To modify the original DataFrame:
# df.drop(columns=['Tax'], inplace=True)

     Name  Age  Salary Department  AnnualSalary SalaryCategory
0     Ali   25   50000         IT        600000       Standard
1    Sara   30   70000         HR        840000         Medium
2   Ahmed   28   60000         IT        720000         Medium
3  Ayesha   35   90000    Finance       1080000           High
4   Bilal   22   45000         HR        540000            Low

## 11. Adding Rows and Combining DataFrames

In [17]:
# Add a single row using loc
df_rows = df[['Name', 'Age', 'Salary', 'Department']].copy()

df_rows.loc[len(df_rows)] = [
    'Hamza', 27, 55000, 'IT'
]

display(df_rows)

     Name  Age  Salary Department
0     Ali   25   50000         IT
1    Sara   30   70000         HR
2   Ahmed   28   60000         IT
3  Ayesha   35   90000    Finance
4   Bilal   22   45000         HR
5   Hamza   27   55000         IT

In [18]:
# Combine multiple DataFrames vertically
df1 = pd.DataFrame({
    'Name': ['Ali', 'Sara'],
    'Salary': [50000, 70000]
})

df2 = pd.DataFrame({
    'Name': ['Ahmed', 'Ayesha'],
    'Salary': [60000, 90000]
})

combined = pd.concat([df1, df2], ignore_index=True)
display(combined)

     Name  Salary
0     Ali   50000
1    Sara   70000
2   Ahmed   60000
3  Ayesha   90000

## 12. Renaming Columns

In [19]:
# Rename selected columns
renamed = df.rename(columns={
    'Age': 'Customer_Age',
    'Salary': 'MonthlySalary'
})

display(renamed.head())

# Rename all columns
# df.columns = ['Name', 'Age', 'Salary', 'Department']

,Name,Customer_Age,MonthlySalary,Department,AnnualSalary,Tax,Adult,SalaryCategory
0,Ali,25,50000,IT,600000,5000.0,Yes,Standard
1,Sara,30,70000,HR,840000,7000.0,Yes,Medium
2,Ahmed,28,60000,IT,720000,6000.0,Yes,Medium
3,Ayesha,35,90000,Finance,1080000,9000.0,Yes,High
4,Bilal,22,45000,HR,540000,4500.0,Yes,Low

## 13. Sorting

In [20]:
# Sort by Salary ascending
display(df.sort_values('Salary'))

# Sort by Salary descending
display(df.sort_values('Salary', ascending=False))

# Sort by multiple columns
display(
    df.sort_values(
        ['Department', 'Salary'],
        ascending=[True, False]
    )
)

     Name  Age  Salary Department  AnnualSalary     Tax Adult SalaryCategory
4   Bilal   22   45000         HR        540000  4500.0   Yes            Low
0     Ali   25   50000         IT        600000  5000.0   Yes       Standard
2   Ahmed   28   60000         IT        720000  6000.0   Yes         Medium
1    Sara   30   70000         HR        840000  7000.0   Yes         Medium
3  Ayesha   35   90000    Finance       1080000  9000.0   Yes           High

     Name  Age  Salary Department  AnnualSalary     Tax Adult SalaryCategory
3  Ayesha   35   90000    Finance       1080000  9000.0   Yes           High
1    Sara   30   70000         HR        840000  7000.0   Yes         Medium
2   Ahmed   28   60000         IT        720000  6000.0   Yes         Medium
0     Ali   25   50000         IT        600000  5000.0   Yes       Standard
4   Bilal   22   45000         HR        540000  4500.0   Yes            Low

     Name  Age  Salary Department  AnnualSalary     Tax Adult SalaryCategory
3  Ayesha   35   90000    Finance       1080000  9000.0   Yes           High
1    Sara   30   70000         HR        840000  7000.0   Yes         Medium
4   Bilal   22   45000         HR        540000  4500.0   Yes            Low
2   Ahmed   28   60000         IT        720000  6000.0   Yes         Medium
0     Ali   25   50000         IT        600000  5000.0   Yes       Standard

## 14. Missing Values

In [ ]:
# Create a small DataFrame containing missing values
missing_df = pd.DataFrame({


})

# Check missing values
display(missing_df.isna())

# Count missing values by column
print(missing_df.isna().sum())

# Percentage of missing values
print(missing_df.isna().mean() * 100)

# Drop rows containing missing values
display(missing_df.dropna())

# Fill all missing values with zero
display(missing_df.fillna(0))

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False  False   False

Name      0
Age       1
Salary    1
dtype: int64
Name       0.0
Age       25.0
Salary    25.0
dtype: float64

     Name   Age   Salary
0     Ali  25.0  50000.0
3  Ayesha  35.0  90000.0

     Name   Age   Salary
0     Ali  25.0  50000.0
1    Sara   0.0  70000.0
2   Ahmed  28.0      0.0
3  Ayesha  35.0  90000.0

In [22]:
# Fill Age missing values with the median
missing_df['Age'] = missing_df['Age'].fillna(
    missing_df['Age'].median()
)

# Fill Salary missing values with the mean
missing_df['Salary'] = missing_df['Salary'].fillna(
    missing_df['Salary'].mean()
)

display(missing_df)

# Forward fill and backward fill
print("Forward fill:")
display(missing_df.ffill())

print("Backward fill:")
display(missing_df.bfill())

     Name   Age   Salary
0     Ali  25.0  50000.0
1    Sara  28.0  70000.0
2   Ahmed  28.0  70000.0
3  Ayesha  35.0  90000.0

Forward fill:

     Name   Age   Salary
0     Ali  25.0  50000.0
1    Sara  28.0  70000.0
2   Ahmed  28.0  70000.0
3  Ayesha  35.0  90000.0

Backward fill:

     Name   Age   Salary
0     Ali  25.0  50000.0
1    Sara  28.0  70000.0
2   Ahmed  28.0  70000.0
3  Ayesha  35.0  90000.0

## 15. Duplicates

In [23]:
duplicate_df = pd.DataFrame({
    'CustomerID': [101, 102, 102, 103, 104, 104],
    'Name': ['Ali', 'Sara', 'Sara', 'Ahmed', 'Ayesha', 'Ayesha']
})

# Identify duplicate rows
print(duplicate_df.duplicated())

# Count duplicate rows
print("Duplicate count:", duplicate_df.duplicated().sum())

# Remove duplicate rows
clean_duplicate_df = duplicate_df.drop_duplicates()

display(clean_duplicate_df)

# Remove duplicates based on a specific column
display(duplicate_df.drop_duplicates(subset=['CustomerID']))

0    False
1    False
2     True
3    False
4    False
5     True
dtype: bool
Duplicate count: 2

   CustomerID    Name
0         101     Ali
1         102    Sara
3         103   Ahmed
4         104  Ayesha

   CustomerID    Name
0         101     Ali
1         102    Sara
3         103   Ahmed
4         104  Ayesha

## 16. String Operations

In [24]:
text_df = pd.DataFrame({
    'Name': [' ali ', 'SARA', 'Ahmed Khan', 'Ayesha'],
    'Email': ['ALI@EXAMPLE.COM', 'sara@test.com', 'ahmed@test.com', 'ayesha@test.com']
})

# Convert to lowercase
text_df['Name_Lower'] = text_df['Name'].str.lower()

# Convert to uppercase
text_df['Name_Upper'] = text_df['Name'].str.upper()

# Capitalize
text_df['Name_Capitalized'] = text_df['Name'].str.capitalize()

# Remove leading/trailing spaces
text_df['Name_Clean'] = text_df['Name'].str.strip()

# String length
text_df['Name_Length'] = text_df['Name'].str.len()

display(text_df)

,Name,Email,Name_Lower,Name_Upper,Name_Capitalized,Name_Clean,Name_Length
0,ali,ALI@EXAMPLE.COM,ali,ALI,ali,ali,5
1,SARA,sara@test.com,sara,SARA,Sara,SARA,4
2,Ahmed Khan,ahmed@test.com,ahmed khan,AHMED KHAN,Ahmed khan,Ahmed Khan,10
3,Ayesha,ayesha@test.com,ayesha,AYESHA,Ayesha,Ayesha,6

In [25]:
# Contains
display(
    text_df[
        text_df['Name'].str.contains('Ali', case=False, na=False)
    ]
)

# Starts with
display(
    text_df[
        text_df['Name'].str.strip().str.startswith('A', na=False)
    ]
)

# Ends with
display(
    text_df[
        text_df['Name'].str.strip().str.endswith('n', na=False)
    ]
)

# Replace text
display(
    text_df['Name'].str.replace('Ali', 'Ahmed', regex=False)
)

# Split text
display(
    text_df['Name'].str.strip().str.split()
)

,Name,Email,Name_Lower,Name_Upper,Name_Capitalized,Name_Clean,Name_Length
0,ali,ALI@EXAMPLE.COM,ali,ALI,ali,ali,5

,Name,Email,Name_Lower,Name_Upper,Name_Capitalized,Name_Clean,Name_Length
2,Ahmed Khan,ahmed@test.com,ahmed khan,AHMED KHAN,Ahmed khan,Ahmed Khan,10
3,Ayesha,ayesha@test.com,ayesha,AYESHA,Ayesha,Ayesha,6

,Name,Email,Name_Lower,Name_Upper,Name_Capitalized,Name_Clean,Name_Length
2,Ahmed Khan,ahmed@test.com,ahmed khan,AHMED KHAN,Ahmed khan,Ahmed Khan,10

0          ali
1          SARA
2    Ahmed Khan
3        Ayesha
Name: Name, dtype: str

0            [ali]
1           [SARA]
2    [Ahmed, Khan]
3         [Ayesha]
Name: Name, dtype: object

## 17. Data Type Conversion

In [26]:
conversion_df = pd.DataFrame({
    'Age': ['25', '30', '28', 'unknown'],
    'Salary': ['50000', '70000', '60000', '90000'],
    'Date': ['2026-01-01', '2026-02-01', '2026-03-01', '2026-04-01']
})

# Convert Age to numeric; invalid values become NaN
conversion_df['Age'] = pd.to_numeric(
    conversion_df['Age'],
    errors='coerce'
)

# Convert Salary to numeric
conversion_df['Salary'] = pd.to_numeric(
    conversion_df['Salary'],
    errors='coerce'
)

# Convert Date to datetime
conversion_df['Date'] = pd.to_datetime(
    conversion_df['Date']
)

print(conversion_df.dtypes)
display(conversion_df)

Age              float64
Salary             int64
Date      datetime64[us]
dtype: object

    Age  Salary       Date
0  25.0   50000 2026-01-01
1  30.0   70000 2026-02-01
2  28.0   60000 2026-03-01
3   NaN   90000 2026-04-01

In [27]:
# astype() can be used when the values are already compatible
example = pd.DataFrame({'Age': [25.0, 30.0, 28.0]})
example['Age'] = example['Age'].astype(int)

display(example)

   Age
0   25
1   30
2   28

## 18. Date and Time Operations

In [28]:
date_df = pd.DataFrame({
    'Date': pd.to_datetime([
        '2026-01-15',
        '2026-02-20',
        '2026-03-10'
    ])
})

# Extract year, month and day
date_df['Year'] = date_df['Date'].dt.year
date_df['Month'] = date_df['Date'].dt.month
date_df['Day'] = date_df['Date'].dt.day

# Day and month names
date_df['DayName'] = date_df['Date'].dt.day_name()
date_df['MonthName'] = date_df['Date'].dt.month_name()

display(date_df)

        Date  Year  Month  Day   DayName MonthName
0 2026-01-15  2026      1   15  Thursday   January
1 2026-02-20  2026      2   20    Friday  February
2 2026-03-10  2026      3   10   Tuesday     March

In [29]:
# Date difference example
date_range_df = pd.DataFrame({
    'Start': pd.to_datetime(['2026-01-01', '2026-02-01']),
    'End': pd.to_datetime(['2026-01-10', '2026-02-15'])
})

date_range_df['Duration'] = (
    date_range_df['End'] - date_range_df['Start']
)

date_range_df['DurationDays'] = (
    date_range_df['Duration'].dt.days
)

display(date_range_df)

       Start        End Duration  DurationDays
0 2026-01-01 2026-01-10   9 days             9
1 2026-02-01 2026-02-15  14 days            14

## 19. Statistical Functions

In [30]:
# Create a numeric Series
salary = df['Salary']

print("Mean:", salary.mean())
print("Median:", salary.median())
print("Mode:")
display(salary.mode())
print("Minimum:", salary.min())
print("Maximum:", salary.max())
print("Standard deviation:", salary.std())
print("Variance:", salary.var())
print("Sum:", salary.sum())
print("Count:", salary.count())
print("75th percentile:", salary.quantile(0.75))

Mean: 63000.0
Median: 60000.0
Mode:

0    45000
1    50000
2    60000
3    70000
4    90000
Name: Salary, dtype: int64

Minimum: 45000
Maximum: 90000
Standard deviation: 17888.54381999832
Variance: 320000000.0
Sum: 315000
Count: 5
75th percentile: 70000.0

## 20. Correlation

In [31]:
# Correlation matrix for numeric columns
display(df.corr(numeric_only=True))

# Correlation between two specific columns
print(
    "Age-Salary correlation:",
    df['Age'].corr(df['Salary'])
)

                   Age    Salary  AnnualSalary       Tax
Age           1.000000  0.988212      0.988212  0.988212
Salary        0.988212  1.000000      1.000000  1.000000
AnnualSalary  0.988212  1.000000      1.000000  1.000000
Tax           0.988212  1.000000      1.000000  1.000000

Age-Salary correlation: 0.9882117688026186

## 21. GroupBy

In [32]:
# Average salary by department
display(
    df.groupby('Department')['Salary'].mean()
)

# Total salary by department
display(
    df.groupby('Department')['Salary'].sum()
)

# Employee count by department
display(
    df.groupby('Department')['Name'].count()
)

Department
Finance    90000.0
HR         57500.0
IT         55000.0
Name: Salary, dtype: float64

Department
Finance     90000
HR         115000
IT         110000
Name: Salary, dtype: int64

Department
Finance    1
HR         2
IT         2
Name: Name, dtype: int64

In [33]:
# Multiple aggregations
display(
    df.groupby('Department')['Salary'].agg(
        ['mean', 'median', 'min', 'max', 'std']
    )
)

# Aggregate different columns with different functions
display(
    df.groupby('Department').agg({
        'Salary': 'mean',
        'Age': 'mean'
    })
)

               mean   median    min    max           std
Department
Finance     90000.0  90000.0  90000  90000           NaN
HR          57500.0  57500.0  45000  70000  17677.669530
IT          55000.0  55000.0  50000  60000   7071.067812

             Salary   Age
Department
Finance     90000.0  35.0
HR          57500.0  26.0
IT          55000.0  26.5

## 22. agg()

In [34]:
# Apply multiple statistics to one column
display(
    df['Salary'].agg([
        'mean',
        'median',
        'min',
        'max',
        'std'
    ])
)

# Custom aggregation using a lambda
salary_range = df['Salary'].agg(
    lambda x: x.max() - x.min()
)

print("Salary range:", salary_range)

mean      63000.00000
median    60000.00000
min       45000.00000
max       90000.00000
std       17888.54382
Name: Salary, dtype: float64

Salary range: 45000

## 23. apply()

In [35]:
# Apply a function to each value in a column
df_apply = df.copy()

df_apply['SalaryWithBonus'] = df_apply['Salary'].apply(
    lambda x: x * 1.10
)

display(df_apply[['Name', 'Salary', 'SalaryWithBonus']])

     Name  Salary  SalaryWithBonus
0     Ali   50000          55000.0
1    Sara   70000          77000.0
2   Ahmed   60000          66000.0
3  Ayesha   90000          99000.0
4   Bilal   45000          49500.0

In [36]:
# Apply a function to each row
df_apply['AgePlusSalary'] = df_apply.apply(
    lambda row: row['Age'] + row['Salary'],
    axis=1
)

display(df_apply[['Name', 'Age', 'Salary', 'AgePlusSalary']])

     Name  Age  Salary  AgePlusSalary
0     Ali   25   50000          50025
1    Sara   30   70000          70030
2   Ahmed   28   60000          60028
3  Ayesha   35   90000          90035
4   Bilal   22   45000          45022

## 24. map()

In [37]:
# Map categorical values to numeric values
gender_df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'Ahmed', 'Ayesha'],
    'Gender': ['Male', 'Female', 'Male', 'Female']
})

gender_df['GenderCode'] = gender_df['Gender'].map({
    'Male': 1,
    'Female': 0
})

display(gender_df)

     Name  Gender  GenderCode
0     Ali    Male           1
1    Sara  Female           0
2   Ahmed    Male           1
3  Ayesha  Female           0

## 25. replace()

In [38]:
city_df = pd.DataFrame({
    'City': ['Lhr', 'Karachi', 'Khi', 'Lahore', 'Isb']
})

# Replace abbreviated values with standardized names
city_df['City'] = city_df['City'].replace({
    'Lhr': 'Lahore',
    'Khi': 'Karachi',
    'Isb': 'Islamabad'
})

display(city_df)

        City
0     Lahore
1    Karachi
2    Karachi
3     Lahore
4  Islamabad

## 26. value_counts()

In [39]:
# Frequency of each department
display(df['Department'].value_counts())

# Percentage distribution
display(
    df['Department'].value_counts(normalize=True) * 100
)

Department
IT         2
HR         2
Finance    1
Name: count, dtype: int64

Department
IT         40.0
HR         40.0
Finance    20.0
Name: proportion, dtype: float64

## 27. Crosstab

In [40]:
cross_df = pd.DataFrame({
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
    'Department': ['IT', 'HR', 'HR', 'Finance', 'IT']
})

# Frequency table
display(
    pd.crosstab(
        cross_df['Gender'],
        cross_df['Department']
    )
)

# Row-wise percentages
display(
    pd.crosstab(
        cross_df['Gender'],
        cross_df['Department'],
        normalize='index'
    ) * 100
)

Department  Finance  HR  IT
Gender
Female            1   1   0
Male              0   1   2

Department  Finance         HR         IT
Gender
Female         50.0  50.000000   0.000000
Male            0.0  33.333333  66.666667

## 28. Merge — SQL JOIN Equivalent

In [41]:
customers = pd.DataFrame({
    'CustomerID': [1, 2, 3],
    'Name': ['Ali', 'Sara', 'Ahmed']
})

orders = pd.DataFrame({
    'CustomerID': [1, 1, 2, 4],
    'Amount': [1000, 2000, 1500, 3000]
})

# Inner join
inner_join = pd.merge(
    customers,
    orders,
    on='CustomerID',
    how='inner'
)

display(inner_join)

# Left join
left_join = pd.merge(
    customers,
    orders,
    on='CustomerID',
    how='left'
)

display(left_join)

# Right join
right_join = pd.merge(
    customers,
    orders,
    on='CustomerID',
    how='right'
)

display(right_join)

# Outer join
outer_join = pd.merge(
    customers,
    orders,
    on='CustomerID',
    how='outer'
)

display(outer_join)

   CustomerID  Name  Amount
0           1   Ali    1000
1           1   Ali    2000
2           2  Sara    1500

   CustomerID   Name  Amount
0           1    Ali  1000.0
1           1    Ali  2000.0
2           2   Sara  1500.0
3           3  Ahmed     NaN

   CustomerID  Name  Amount
0           1   Ali    1000
1           1   Ali    2000
2           2  Sara    1500
3           4   NaN    3000

   CustomerID   Name  Amount
0           1    Ali  1000.0
1           1    Ali  2000.0
2           2   Sara  1500.0
3           3  Ahmed     NaN
4           4    NaN  3000.0

## 29. Concatenation

In [42]:
# Vertical concatenation
display(
    pd.concat([df1, df2], ignore_index=True)
)

# Horizontal concatenation
horizontal = pd.concat(
    [df1.reset_index(drop=True),
     df2.reset_index(drop=True)],
    axis=1
)

display(horizontal)

     Name  Salary
0     Ali   50000
1    Sara   70000
2   Ahmed   60000
3  Ayesha   90000

   Name  Salary    Name  Salary
0   Ali   50000   Ahmed   60000
1  Sara   70000  Ayesha   90000

## 30. Pivot Tables

In [43]:
sales_df = pd.DataFrame({
    'Region': ['North', 'North', 'South', 'South', 'North', 'South'],
    'Product': ['A', 'B', 'A', 'B', 'A', 'B'],
    'Sales': [100, 150, 120, 180, 130, 200]
})

# Excel-style pivot table
pivot = pd.pivot_table(
    sales_df,
    values='Sales',
    index='Region',
    columns='Product',
    aggfunc='sum'
)

display(pivot)

Product    A    B
Region
North    230  150
South    120  380

## 31. Reshaping: pivot(), stack(), unstack()

In [44]:
# pivot() requires combinations of index/columns to be unique
pivot_simple = sales_df.pivot(
    index='Region',
    columns='Product',
    values='Sales'
)

display(pivot_simple)

# Convert columns into an index level
stacked = pivot_simple.stack()
display(stacked)

# Reverse the operation
unstacked = stacked.unstack()
display(unstacked)

ValueError: Index contains duplicate entries, cannot reshape

## 32. melt() — Wide to Long

In [ ]:
wide_df = pd.DataFrame({
    'Name': ['Ali', 'Sara'],
    'Math': [80, 90],
    'Science': [85, 88],
    'English': [78, 92]
})

long_df = pd.melt(
    wide_df,
    id_vars=['Name'],
    var_name='Subject',
    value_name='Marks'
)

display(long_df)

## 33. Index Operations

In [ ]:
index_df = df.set_index('Name')

print("DataFrame with Name as index:")
display(index_df)

# Reset the index
reset_df = index_df.reset_index()

print("Index reset:")
display(reset_df)

In [ ]:
# Set an index name
reset_df.index.name = 'RowID'

display(reset_df)

## 34. Sampling

In [ ]:
# Randomly select 2 rows
display(df.sample(2))

# Randomly select 50% of the data
display(df.sample(frac=0.5))

# Use random_state for reproducible results
display(df.sample(2, random_state=42))

## 35. Train/Test Split for Machine Learning

In [ ]:
# scikit-learn is normally preferred for train/test splitting
from sklearn.model_selection import train_test_split

ml_df = pd.DataFrame({
    'Age': [22, 25, 28, 30, 35, 40, 45, 50],
    'Salary': [40000, 50000, 60000, 70000, 80000, 90000, 100000, 120000],
    'Purchased': [0, 0, 1, 1, 1, 1, 1, 1]
})

X = ml_df[['Age', 'Salary']]
y = ml_df['Purchased']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)

print("X_train:")
display(X_train)

print("X_test:")
display(X_test)

print("y_train:")
display(y_train)

print("y_test:")
display(y_test)

## 36. Outlier Detection using IQR

In [ ]:
outlier_df = pd.DataFrame({
    'Salary': [40000, 45000, 50000, 52000, 55000, 60000,
               65000, 70000, 75000, 200000]
})

# Calculate first and third quartiles
Q1 = outlier_df['Salary'].quantile(0.25)
Q3 = outlier_df['Salary'].quantile(0.75)

# Interquartile range
IQR = Q3 - Q1

# Define lower and upper boundaries
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify outliers
outliers = outlier_df[
    (outlier_df['Salary'] < lower_bound) |
    (outlier_df['Salary'] > upper_bound)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

display(outliers)

## 37. Ranking

In [ ]:
rank_df = df[['Name', 'Salary']].copy()

# Rank highest salary as rank 1
rank_df['SalaryRank'] = rank_df['Salary'].rank(
    ascending=False,
    method='dense'
)

display(rank_df.sort_values('SalaryRank'))

## 38. where() and mask()

In [ ]:
where_df = pd.DataFrame({
    'Salary': [40000, 55000, 70000, 45000, 90000]
})

# Keep values where Salary > 50,000; otherwise replace with 50,000
where_df['Salary_Where'] = where_df['Salary'].where(
    where_df['Salary'] > 50000,
    50000
)

# Replace values where Salary < 50,000
where_df['Salary_Mask'] = where_df['Salary'].mask(
    where_df['Salary'] < 50000,
    50000
)

display(where_df)

## 39. Unique Values

In [ ]:
# Get unique values
print(df['Department'].unique())

# Count unique values
print("Number of unique departments:",
      df['Department'].nunique())

## 40. Cumulative Operations

In [ ]:
time_df = pd.DataFrame({
    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May'],
    'Sales': [100, 150, 120, 180, 200]
})

# Cumulative sum
time_df['CumulativeSales'] = time_df['Sales'].cumsum()

# Cumulative maximum
time_df['CumulativeMax'] = time_df['Sales'].cummax()

# Cumulative minimum
time_df['CumulativeMin'] = time_df['Sales'].cummin()

display(time_df)

## 41. Rolling / Moving Average

In [ ]:
# 3-period moving average
time_df['MovingAverage_3'] = (
    time_df['Sales'].rolling(3).mean()
)

# 3-period moving sum
time_df['MovingSum_3'] = (
    time_df['Sales'].rolling(3).sum()
)

display(time_df)

## 42. shift() and pct_change()

In [ ]:
# Previous month's sales
time_df['PreviousSales'] = time_df['Sales'].shift(1)

# Next month's sales
time_df['NextSales'] = time_df['Sales'].shift(-1)

# Percentage change from previous period
time_df['GrowthPercent'] = (
    time_df['Sales'].pct_change() * 100
)

display(time_df)

## 43. Ranking Within Groups

In [ ]:
group_rank_df = pd.DataFrame({
    'Department': ['IT', 'IT', 'IT', 'HR', 'HR'],
    'Name': ['Ali', 'Ahmed', 'Bilal', 'Sara', 'Ayesha'],
    'Salary': [150000, 120000, 100000, 110000, 90000]
})

# Rank employees within each department
group_rank_df['DepartmentRank'] = (
    group_rank_df
    .groupby('Department')['Salary']
    .rank(ascending=False, method='dense')
)

display(
    group_rank_df.sort_values(
        ['Department', 'DepartmentRank']
    )
)

## 44. Conditional Selection with loc

In [ ]:
loc_df = df.copy()

# Select only Name and Salary where Salary > 50,000
display(
    loc_df.loc[
        loc_df['Salary'] > 50000,
        ['Name', 'Salary']
    ]
)

# Create a category using loc
loc_df['Category'] = 'Standard'

loc_df.loc[
    loc_df['Salary'] > 70000,
    'Category'
] = 'High'

display(loc_df[['Name', 'Salary', 'Category']])

## 45. Convert DataFrame to NumPy

In [ ]:
# Convert DataFrame to a NumPy array
X_array = df[['Age', 'Salary']].to_numpy()

print(type(X_array))
print(X_array)

## 46. Convert DataFrame to Dictionary / List

In [ ]:
# Convert DataFrame to dictionary
dictionary_data = df.to_dict()

# Convert each row into a dictionary
records = df.to_dict(orient='records')

print("Dictionary:")
print(dictionary_data)

print("\nRecords:")
print(records)

# Convert a Series to a Python list
names_list = df['Name'].tolist()

print("\nNames list:")
print(names_list)

## 47. One-Hot Encoding

In [ ]:
encoding_df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'Ahmed', 'Ayesha'],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'City': ['Lahore', 'Karachi', 'Lahore', 'Islamabad']
})

# Convert categorical variables into dummy/indicator columns
encoded_df = pd.get_dummies(
    encoding_df,
    columns=['Gender', 'City'],
    dtype=int
)

display(encoded_df)

## 48. Binning with cut()

In [ ]:
age_df = pd.DataFrame({
    'Age': [5, 15, 22, 28, 35, 45, 60, 75]
})

# Create age groups using fixed intervals
age_df['AgeGroup'] = pd.cut(
    age_df['Age'],
    bins=[0, 18, 30, 50, 100],
    labels=['Child', 'Young', 'Adult', 'Senior']
)

display(age_df)

## 49. Quantile Binning with qcut()

In [ ]:
salary_df = pd.DataFrame({
    'Salary': [30000, 40000, 50000, 60000,
               70000, 80000, 100000, 150000]
})

# Divide data into four equally populated groups
salary_df['SalaryGroup'] = pd.qcut(
    salary_df['Salary'],
    q=4,
    labels=['Low', 'Medium', 'High', 'Very High']
)

display(salary_df)

## 50. explode()

In [ ]:
skills_df = pd.DataFrame({
    'Name': ['Ali', 'Sara'],
    'Skills': [
        ['Python', 'SQL'],
        ['Power BI', 'Excel']
    ]
})

# Convert list values into separate rows
exploded_df = skills_df.explode('Skills')

display(exploded_df)

## 51. Working with Large CSV Files

In [ ]:
# Read a large CSV in chunks instead of loading it all into memory
# chunks = pd.read_csv('large_file.csv', chunksize=10000)

# Process each chunk
# for chunk in chunks:
#     print(chunk.shape)

print("Chunk-processing template is commented because no external large file is required for this notebook.")

## 52. Read Selected Columns / Rows

In [ ]:
# Read only selected columns from a CSV
# df = pd.read_csv(
#     'data.csv',
#     usecols=['Name', 'Age', 'Salary']
# )

# Read only the first 1,000 rows
# df = pd.read_csv(
#     'data.csv',
#     nrows=1000
# )

print("Templates are commented because the external CSV file is not part of this notebook.")

## 53. Excel Sheet Operations

In [ ]:
# Read one Excel sheet
# df = pd.read_excel(
#     'data.xlsx',
#     sheet_name='Sheet1'
# )

# Read all Excel sheets
# all_sheets = pd.read_excel(
#     'data.xlsx',
#     sheet_name=None
# )

# all_sheets is a dictionary:
# {
#     'Sheet1': DataFrame,
#     'Sheet2': DataFrame,
#     ...
# }

print("Excel templates are commented because no external workbook is required.")

#  Pandas + Machine Learning Workflow

A typical Data Science workflow looks like this:

```text
Raw Data
   ↓
pd.read_csv() / pd.read_excel()
   ↓
head() / info() / describe()
   ↓
Data Cleaning
   ↓
isna() / fillna() / dropna()
   ↓
Duplicate Removal
   ↓
drop_duplicates()
   ↓
Data Transformation
   ↓
astype() / map() / apply()
   ↓
Feature Engineering
   ↓
Create useful features
   ↓
Encoding
   ↓
pd.get_dummies()
   ↓
Analysis
   ↓
groupby() / pivot_table() / corr()
   ↓
Features (X) + Target (y)
   ↓
train_test_split()
   ↓
Machine Learning Model
```

# ⭐ Most Important Pandas Commands for Students

If students cannot memorize everything, prioritize these:

### Data Input / Output
- `pd.read_csv()`
- `pd.read_excel()`
- `df.to_csv()`
- `df.to_excel()`

### Inspection
- `df.head()`
- `df.tail()`
- `df.shape`
- `df.columns`
- `df.info()`
- `df.describe()`
- `df.dtypes`

### Selection / Filtering
- `df['column']`
- `df[['col1', 'col2']]`
- `df.loc[]`
- `df.iloc[]`
- Boolean filtering
- `isin()`
- `between()`
- `query()`

### Cleaning
- `isna()`
- `fillna()`
- `dropna()`
- `drop_duplicates()`
- `astype()`
- `to_numeric()`
- `to_datetime()`

### Analysis
- `value_counts()`
- `groupby()`
- `agg()`
- `pivot_table()`
- `crosstab()`
- `corr()`

### Transformation
- `apply()`
- `map()`
- `replace()`
- `sort_values()`
- `pd.get_dummies()`

### Combining Data
- `pd.concat()`
- `pd.merge()`

### Time Series
- `shift()`
- `pct_change()`
- `rolling()`
- `cumsum()`

### ML Preparation
- `sample()`
- `to_numpy()`
- `train_test_split()`

# 📝 Practice Exercise

Using the DataFrame below, practice the following:

1. Display the first 5 rows.
2. Find the number of rows and columns.
3. Find the average salary.
4. Find employees with salary > 60,000.
5. Find employees from IT.
6. Sort employees by salary descending.
7. Add an `AnnualSalary` column.
8. Create a `SalaryCategory` column.
9. Calculate average salary by department.
10. Find the correlation between Age and Salary.
11. Create a salary rank.
12. Convert the data into NumPy format.

In [ ]:
# Practice dataset
practice_df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'Ahmed', 'Ayesha', 'Bilal', 'Hina'],
    'Age': [25, 30, 28, 35, 22, 31],
    'Salary': [50000, 70000, 60000, 90000, 45000, 75000],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR', 'IT']
})

practice_df

## End of Notebook

This notebook is designed as a **Pandas teaching/reference notebook** for Data Analytics, Data Science and Machine Learning.

Next recommended learning sequence:

**Python → NumPy → Pandas → Matplotlib/Seaborn → Statistics → Scikit-learn → Machine Learning**